void main(){
  Future(() {
    throw Exception('Algo sali√≥ mal');
  }).then((_){
    print('Exito!');
  }).catchError((error){
    print('Error: $error');
  });
}